In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2

In [4]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y*y*3


In [7]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [9]:
print(z.grad_fn)

In [10]:
print(y.grad_fn)

In [11]:
out = z.mean()

In [12]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [13]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
